---
name: "Deploy to Amazon Elastic Beanstalk"
description: "Deploy to Amazon Elastic Beanstalk"

inputs:
  aws-access-key-id:
    description: "AWS access key id"
    required: true
  aws-secret-access-key:
    description: "AWS secret access key"
    required: true
  aws-region:
    description: "AWS region"
    required: true
  aws-account-id:
    description: "AWS account id"
    required: true

runs:
  using: "composite"
  steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ inputs.aws-access-key-id }}
        aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
        aws-region: ${{ inputs.aws-region }}
