---
name: "Deploy to Amazon Elastic Beanstalk"
description: "Deploy to Amazon Elastic Beanstalk"

inputs:
  env:
    description: "Provide the environment to deploy to [develop, release, production]"
    required: false
    default: develop

runs:
  # using: "composite"
  # steps:
  #   - name: Validate composer.json and composer.lock
  #     run: composer validate --strict

  #   - name: Cache Composer packages
  #     id: composer-cache
  #     uses: actions/cache@v3
  #     with:
  #       path: vendor
  #       key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
  #       restore-keys: |
  #         ${{ runner.os }}-php-

  #   - name: Install dependencies
  #     run: composer install --prefer-dist --no-progress --ignore-platform-req=ext-soap --ignore-platform-req=ext-gd

  #   - name: Create missing folders
  #     run: mkdir -p api/{runtime,web/assets} frontend/runtime

  #   - name: Init Yii application
  #     run: php init --env=Production --overwrite=n

  - using: node16
    main: action/index.js

  - using: node16
    main: action/index.js
