---
name: "Deploy to Amazon Elastic Beanstalk"
description: "Deploy to Amazon Elastic Beanstalk"

inputs:
  aws-access-key-id:
    description: "AWS access key id"
    required: true
  aws-secret-access-key:
    description: "AWS secret access key"
    required: true
  aws-region:
    description: "AWS region"
    required: true
  aws-account-id:
    description: "AWS account id"
    required: true
  environment:
    description: "Environment where to deploy [develop, release, production]"
    required: true
  application:
    description: "Application to deploy [frontend, api]"
    required: true

runs:
  using: "composite"
  steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ inputs.aws-access-key-id }}
        aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
        aws-region: ${{ inputs.aws-region }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Test sha
      shell: bash
      run: echo ${{github.sha}}

    # - name: Build, tag, and push image to Amazon ECR
    #   id: build-image
    #   env:
    #     CR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
    #   run: |
    #     docker build -f $REPOSITORY/Dockerfile -t $ECR_REGISTRY/$REPOSITORY:$IMAGE_TAG .
    #     docker push $ECR_REGISTRY/$REPOSITORY:$IMAGE_TAG
    #     echo "::set-output name=image::$ECR_REGISTRY/$REPOSITORY:$IMAGE_TAG"
